//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNetzAWebServiceClient.WS_VersUnterbrechungGas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransBeginnArtEnum", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public enum TransBeginnArtEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EchtDaten = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TestVerweigert = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TestGesperrt = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TestAusserBetrieb = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TestAkzeptiert = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TestNichtAkzeptiert = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TestFehler = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Antwort", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenAntwort))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenAntwort))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenAntwort))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BNetzAWebServiceClient.WS_VersUnterbrechungGas.PruefAntwort))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransAntwort))]
    public partial class Antwort : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransStatusEnum StatusWSField;
        
        private int MeldungscodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeldungField;
        
        private bool IstTestField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransStatusEnum StatusWS {
            get {
                return this.StatusWSField;
            }
            set {
                if ((this.StatusWSField.Equals(value) != true)) {
                    this.StatusWSField = value;
                    this.RaisePropertyChanged("StatusWS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Meldungscode {
            get {
                return this.MeldungscodeField;
            }
            set {
                if ((this.MeldungscodeField.Equals(value) != true)) {
                    this.MeldungscodeField = value;
                    this.RaisePropertyChanged("Meldungscode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Meldung {
            get {
                return this.MeldungField;
            }
            set {
                if ((object.ReferenceEquals(this.MeldungField, value) != true)) {
                    this.MeldungField = value;
                    this.RaisePropertyChanged("Meldung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool IstTest {
            get {
                return this.IstTestField;
            }
            set {
                if ((this.IstTestField.Equals(value) != true)) {
                    this.IstTestField = value;
                    this.RaisePropertyChanged("IstTest");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransUnterbrechungenAntwort", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    [System.SerializableAttribute()]
    public partial class TransUnterbrechungenAntwort : BNetzAWebServiceClient.WS_VersUnterbrechungGas.Antwort {
        
        private int AnzahlEmpfangenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AnzahlEmpfangen {
            get {
                return this.AnzahlEmpfangenField;
            }
            set {
                if ((this.AnzahlEmpfangenField.Equals(value) != true)) {
                    this.AnzahlEmpfangenField = value;
                    this.RaisePropertyChanged("AnzahlEmpfangen");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RueckgabeNetzdatenAntwort", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    [System.SerializableAttribute()]
    public partial class RueckgabeNetzdatenAntwort : BNetzAWebServiceClient.WS_VersUnterbrechungGas.Antwort {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BNetzAWebServiceClient.WS_VersUnterbrechungGas.Netzdaten NetzdatenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.Netzdaten Netzdaten {
            get {
                return this.NetzdatenField;
            }
            set {
                if ((object.ReferenceEquals(this.NetzdatenField, value) != true)) {
                    this.NetzdatenField = value;
                    this.RaisePropertyChanged("Netzdaten");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RueckgabeUnterbrechungenAntwort", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    [System.SerializableAttribute()]
    public partial class RueckgabeUnterbrechungenAntwort : BNetzAWebServiceClient.WS_VersUnterbrechungGas.Antwort {
        
        private int AnzahlUnterbrechungenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BNetzAWebServiceClient.WS_VersUnterbrechungGas.Unterbrechung[] UnterbrechungenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AnzahlUnterbrechungen {
            get {
                return this.AnzahlUnterbrechungenField;
            }
            set {
                if ((this.AnzahlUnterbrechungenField.Equals(value) != true)) {
                    this.AnzahlUnterbrechungenField = value;
                    this.RaisePropertyChanged("AnzahlUnterbrechungen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.Unterbrechung[] Unterbrechungen {
            get {
                return this.UnterbrechungenField;
            }
            set {
                if ((object.ReferenceEquals(this.UnterbrechungenField, value) != true)) {
                    this.UnterbrechungenField = value;
                    this.RaisePropertyChanged("Unterbrechungen");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PruefAntwort", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    [System.SerializableAttribute()]
    public partial class PruefAntwort : BNetzAWebServiceClient.WS_VersUnterbrechungGas.Antwort {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BNetzAWebServiceClient.WS_VersUnterbrechungGas.Fehler[] FehlerlisteField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.Fehler[] Fehlerliste {
            get {
                return this.FehlerlisteField;
            }
            set {
                if ((object.ReferenceEquals(this.FehlerlisteField, value) != true)) {
                    this.FehlerlisteField = value;
                    this.RaisePropertyChanged("Fehlerliste");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BeginnTransAntwort", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    [System.SerializableAttribute()]
    public partial class BeginnTransAntwort : BNetzAWebServiceClient.WS_VersUnterbrechungGas.Antwort {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransNrField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TransNr {
            get {
                return this.TransNrField;
            }
            set {
                if ((object.ReferenceEquals(this.TransNrField, value) != true)) {
                    this.TransNrField = value;
                    this.RaisePropertyChanged("TransNr");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransStatusEnum", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public enum TransStatusEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NichtGesetzt = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Akzeptiert = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Verweigert = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gesperrt = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AusserBetrieb = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fehler = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NichtAkzeptiert = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Netzdaten", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    [System.SerializableAttribute()]
    public partial class Netzdaten : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vug_Bericht_TextField;
        
        private int vug_ANZ_LVField;
        
        private int vug_SUM_LSTField;
        
        private int vug_SUM_KAP_VORField;
        
        private int vug_SUM_KAP_NACHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vug_kommentar_textField;
        
        private decimal A_qu_kg1Field;
        
        private decimal A_qu_kg2Field;
        
        private decimal a_OptionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vug_ANSPRECHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vug_KontaktField;
        
        private int Vug_NB_ArtField;
        
        private BNetzAWebServiceClient.WS_VersUnterbrechungGas.Dopplung vug_dopplungField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string vug_Bericht_Text {
            get {
                return this.vug_Bericht_TextField;
            }
            set {
                if ((object.ReferenceEquals(this.vug_Bericht_TextField, value) != true)) {
                    this.vug_Bericht_TextField = value;
                    this.RaisePropertyChanged("vug_Bericht_Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int vug_ANZ_LV {
            get {
                return this.vug_ANZ_LVField;
            }
            set {
                if ((this.vug_ANZ_LVField.Equals(value) != true)) {
                    this.vug_ANZ_LVField = value;
                    this.RaisePropertyChanged("vug_ANZ_LV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int vug_SUM_LST {
            get {
                return this.vug_SUM_LSTField;
            }
            set {
                if ((this.vug_SUM_LSTField.Equals(value) != true)) {
                    this.vug_SUM_LSTField = value;
                    this.RaisePropertyChanged("vug_SUM_LST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int vug_SUM_KAP_VOR {
            get {
                return this.vug_SUM_KAP_VORField;
            }
            set {
                if ((this.vug_SUM_KAP_VORField.Equals(value) != true)) {
                    this.vug_SUM_KAP_VORField = value;
                    this.RaisePropertyChanged("vug_SUM_KAP_VOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int vug_SUM_KAP_NACH {
            get {
                return this.vug_SUM_KAP_NACHField;
            }
            set {
                if ((this.vug_SUM_KAP_NACHField.Equals(value) != true)) {
                    this.vug_SUM_KAP_NACHField = value;
                    this.RaisePropertyChanged("vug_SUM_KAP_NACH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string vug_kommentar_text {
            get {
                return this.vug_kommentar_textField;
            }
            set {
                if ((object.ReferenceEquals(this.vug_kommentar_textField, value) != true)) {
                    this.vug_kommentar_textField = value;
                    this.RaisePropertyChanged("vug_kommentar_text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal A_qu_kg1 {
            get {
                return this.A_qu_kg1Field;
            }
            set {
                if ((this.A_qu_kg1Field.Equals(value) != true)) {
                    this.A_qu_kg1Field = value;
                    this.RaisePropertyChanged("A_qu_kg1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal A_qu_kg2 {
            get {
                return this.A_qu_kg2Field;
            }
            set {
                if ((this.A_qu_kg2Field.Equals(value) != true)) {
                    this.A_qu_kg2Field = value;
                    this.RaisePropertyChanged("A_qu_kg2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal a_Optional {
            get {
                return this.a_OptionalField;
            }
            set {
                if ((this.a_OptionalField.Equals(value) != true)) {
                    this.a_OptionalField = value;
                    this.RaisePropertyChanged("a_Optional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string vug_ANSPRECH {
            get {
                return this.vug_ANSPRECHField;
            }
            set {
                if ((object.ReferenceEquals(this.vug_ANSPRECHField, value) != true)) {
                    this.vug_ANSPRECHField = value;
                    this.RaisePropertyChanged("vug_ANSPRECH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string vug_Kontakt {
            get {
                return this.vug_KontaktField;
            }
            set {
                if ((object.ReferenceEquals(this.vug_KontaktField, value) != true)) {
                    this.vug_KontaktField = value;
                    this.RaisePropertyChanged("vug_Kontakt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int Vug_NB_Art {
            get {
                return this.Vug_NB_ArtField;
            }
            set {
                if ((this.Vug_NB_ArtField.Equals(value) != true)) {
                    this.Vug_NB_ArtField = value;
                    this.RaisePropertyChanged("Vug_NB_Art");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.Dopplung vug_dopplung {
            get {
                return this.vug_dopplungField;
            }
            set {
                if ((this.vug_dopplungField.Equals(value) != true)) {
                    this.vug_dopplungField = value;
                    this.RaisePropertyChanged("vug_dopplung");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dopplung", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public enum Dopplung : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NichtGesetzt = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeineDopplung = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DopplungVorhanden = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Unterbrechung", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    [System.SerializableAttribute()]
    public partial class Unterbrechung : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vug_nb_nameField;
        
        private System.DateTime vug_BeginndatumField;
        
        private System.DateTime vug_BeginnZeitField;
        
        private int vug_DauerField;
        
        private BNetzAWebServiceClient.WS_VersUnterbrechungGas.UnterbrechungsAnlassEnum stAnlassIDField;
        
        private int vug_EGField;
        
        private BNetzAWebServiceClient.WS_VersUnterbrechungGas.UnterbrechungsArtEnum UnterbrechungsArtField;
        
        private int vug_AUSM_EG1Field;
        
        private int vug_AUSM_EG2Field;
        
        private int vug_KMIN_EG1Field;
        
        private int vug_KMIN_EG2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vug_ANMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vug_ETSOField;
        
        private int LfdNrField;
        
        private BNetzAWebServiceClient.WS_VersUnterbrechungGas.Betroffen vug_NB_betroffenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string vug_nb_name {
            get {
                return this.vug_nb_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.vug_nb_nameField, value) != true)) {
                    this.vug_nb_nameField = value;
                    this.RaisePropertyChanged("vug_nb_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime vug_Beginndatum {
            get {
                return this.vug_BeginndatumField;
            }
            set {
                if ((this.vug_BeginndatumField.Equals(value) != true)) {
                    this.vug_BeginndatumField = value;
                    this.RaisePropertyChanged("vug_Beginndatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime vug_BeginnZeit {
            get {
                return this.vug_BeginnZeitField;
            }
            set {
                if ((this.vug_BeginnZeitField.Equals(value) != true)) {
                    this.vug_BeginnZeitField = value;
                    this.RaisePropertyChanged("vug_BeginnZeit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int vug_Dauer {
            get {
                return this.vug_DauerField;
            }
            set {
                if ((this.vug_DauerField.Equals(value) != true)) {
                    this.vug_DauerField = value;
                    this.RaisePropertyChanged("vug_Dauer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.UnterbrechungsAnlassEnum stAnlassID {
            get {
                return this.stAnlassIDField;
            }
            set {
                if ((this.stAnlassIDField.Equals(value) != true)) {
                    this.stAnlassIDField = value;
                    this.RaisePropertyChanged("stAnlassID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int vug_EG {
            get {
                return this.vug_EGField;
            }
            set {
                if ((this.vug_EGField.Equals(value) != true)) {
                    this.vug_EGField = value;
                    this.RaisePropertyChanged("vug_EG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.UnterbrechungsArtEnum UnterbrechungsArt {
            get {
                return this.UnterbrechungsArtField;
            }
            set {
                if ((this.UnterbrechungsArtField.Equals(value) != true)) {
                    this.UnterbrechungsArtField = value;
                    this.RaisePropertyChanged("UnterbrechungsArt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int vug_AUSM_EG1 {
            get {
                return this.vug_AUSM_EG1Field;
            }
            set {
                if ((this.vug_AUSM_EG1Field.Equals(value) != true)) {
                    this.vug_AUSM_EG1Field = value;
                    this.RaisePropertyChanged("vug_AUSM_EG1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int vug_AUSM_EG2 {
            get {
                return this.vug_AUSM_EG2Field;
            }
            set {
                if ((this.vug_AUSM_EG2Field.Equals(value) != true)) {
                    this.vug_AUSM_EG2Field = value;
                    this.RaisePropertyChanged("vug_AUSM_EG2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int vug_KMIN_EG1 {
            get {
                return this.vug_KMIN_EG1Field;
            }
            set {
                if ((this.vug_KMIN_EG1Field.Equals(value) != true)) {
                    this.vug_KMIN_EG1Field = value;
                    this.RaisePropertyChanged("vug_KMIN_EG1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int vug_KMIN_EG2 {
            get {
                return this.vug_KMIN_EG2Field;
            }
            set {
                if ((this.vug_KMIN_EG2Field.Equals(value) != true)) {
                    this.vug_KMIN_EG2Field = value;
                    this.RaisePropertyChanged("vug_KMIN_EG2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string vug_ANM {
            get {
                return this.vug_ANMField;
            }
            set {
                if ((object.ReferenceEquals(this.vug_ANMField, value) != true)) {
                    this.vug_ANMField = value;
                    this.RaisePropertyChanged("vug_ANM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string vug_ETSO {
            get {
                return this.vug_ETSOField;
            }
            set {
                if ((object.ReferenceEquals(this.vug_ETSOField, value) != true)) {
                    this.vug_ETSOField = value;
                    this.RaisePropertyChanged("vug_ETSO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int LfdNr {
            get {
                return this.LfdNrField;
            }
            set {
                if ((this.LfdNrField.Equals(value) != true)) {
                    this.LfdNrField = value;
                    this.RaisePropertyChanged("LfdNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.Betroffen vug_NB_betroffen {
            get {
                return this.vug_NB_betroffenField;
            }
            set {
                if ((this.vug_NB_betroffenField.Equals(value) != true)) {
                    this.vug_NB_betroffenField = value;
                    this.RaisePropertyChanged("vug_NB_betroffen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnterbrechungsAnlassEnum", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public enum UnterbrechungsAnlassEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NichtGesetzt = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VD = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VN = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FS = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HG = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        US = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZW = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IM = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IA = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GS = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnterbrechungsArtEnum", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public enum UnterbrechungsArtEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NichtGesetzt = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Geplant = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ungeplant = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Betroffen", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public enum Betroffen : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NichtGesetzt = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Letztverbraucher = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        nachgelagerterNetzbetreiber = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fehler", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    [System.SerializableAttribute()]
    public partial class Fehler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private BNetzAWebServiceClient.WS_VersUnterbrechungGas.Fehlerart FehlerArtField;
        
        private int FehlerNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BeschreibungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BezeichnungField;
        
        private int LaufendenummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NNrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.Fehlerart FehlerArt {
            get {
                return this.FehlerArtField;
            }
            set {
                if ((this.FehlerArtField.Equals(value) != true)) {
                    this.FehlerArtField = value;
                    this.RaisePropertyChanged("FehlerArt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int FehlerNummer {
            get {
                return this.FehlerNummerField;
            }
            set {
                if ((this.FehlerNummerField.Equals(value) != true)) {
                    this.FehlerNummerField = value;
                    this.RaisePropertyChanged("FehlerNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Beschreibung {
            get {
                return this.BeschreibungField;
            }
            set {
                if ((object.ReferenceEquals(this.BeschreibungField, value) != true)) {
                    this.BeschreibungField = value;
                    this.RaisePropertyChanged("Beschreibung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Bezeichnung {
            get {
                return this.BezeichnungField;
            }
            set {
                if ((object.ReferenceEquals(this.BezeichnungField, value) != true)) {
                    this.BezeichnungField = value;
                    this.RaisePropertyChanged("Bezeichnung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Laufendenummer {
            get {
                return this.LaufendenummerField;
            }
            set {
                if ((this.LaufendenummerField.Equals(value) != true)) {
                    this.LaufendenummerField = value;
                    this.RaisePropertyChanged("Laufendenummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NNr {
            get {
                return this.NNrField;
            }
            set {
                if ((object.ReferenceEquals(this.NNrField, value) != true)) {
                    this.NNrField = value;
                    this.RaisePropertyChanged("NNr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fehlerart", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public enum Fehlerart : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NichtGesetzt = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unterbrechung = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Einmalig = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas", ConfigurationName="WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap")]
    public interface WS_VersUnterbrechungGasSoap {
        
        // CODEGEN: Generating message contract since element name kNr from namespace https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas/BeginnTransaktion", ReplyAction="*")]
        BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransaktionResponse BeginnTransaktion(BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransaktionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas/BeginnTransaktion", ReplyAction="*")]
        System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransaktionResponse> BeginnTransaktionAsync(BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransaktionRequest request);
        
        // CODEGEN: Generating message contract since element name transNr from namespace https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas/TransNetzdaten", ReplyAction="*")]
        BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransNetzdatenResponse TransNetzdaten(BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransNetzdatenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas/TransNetzdaten", ReplyAction="*")]
        System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransNetzdatenResponse> TransNetzdatenAsync(BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransNetzdatenRequest request);
        
        // CODEGEN: Generating message contract since element name transNr from namespace https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas/TransUnterbrechungen", ReplyAction="*")]
        BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenResponse TransUnterbrechungen(BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas/TransUnterbrechungen", ReplyAction="*")]
        System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenResponse> TransUnterbrechungenAsync(BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenRequest request);
        
        // CODEGEN: Generating message contract since element name transNr from namespace https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas/RueckgabeNetzdaten", ReplyAction="*")]
        BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenResponse RueckgabeNetzdaten(BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas/RueckgabeNetzdaten", ReplyAction="*")]
        System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenResponse> RueckgabeNetzdatenAsync(BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenRequest request);
        
        // CODEGEN: Generating message contract since element name transNr from namespace https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas/RueckgabeUnterbrechungen", ReplyAction="*")]
        BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenResponse RueckgabeUnterbrechungen(BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas/RueckgabeUnterbrechungen", ReplyAction="*")]
        System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenResponse> RueckgabeUnterbrechungenAsync(BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenRequest request);
        
        // CODEGEN: Generating message contract since element name transNr from namespace https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas/AbschlussTransaktion", ReplyAction="*")]
        BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbschlussTransaktionResponse AbschlussTransaktion(BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbschlussTransaktionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas/AbschlussTransaktion", ReplyAction="*")]
        System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbschlussTransaktionResponse> AbschlussTransaktionAsync(BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbschlussTransaktionRequest request);
        
        // CODEGEN: Generating message contract since element name transNr from namespace https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas/AbbruchTransaktion", ReplyAction="*")]
        BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbbruchTransaktionResponse AbbruchTransaktion(BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbbruchTransaktionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas/AbbruchTransaktion", ReplyAction="*")]
        System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbbruchTransaktionResponse> AbbruchTransaktionAsync(BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbbruchTransaktionRequest request);
        
        // CODEGEN: Generating message contract since element name transNr from namespace https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas/ErgebnisPruefung", ReplyAction="*")]
        BNetzAWebServiceClient.WS_VersUnterbrechungGas.ErgebnisPruefungResponse ErgebnisPruefung(BNetzAWebServiceClient.WS_VersUnterbrechungGas.ErgebnisPruefungRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas/ErgebnisPruefung", ReplyAction="*")]
        System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.ErgebnisPruefungResponse> ErgebnisPruefungAsync(BNetzAWebServiceClient.WS_VersUnterbrechungGas.ErgebnisPruefungRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BeginnTransaktionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BeginnTransaktion", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas", Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransaktionRequestBody Body;
        
        public BeginnTransaktionRequest() {
        }
        
        public BeginnTransaktionRequest(BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransaktionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public partial class BeginnTransaktionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int bNR;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string kNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int nNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int berichtsJahr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool leermeldung;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int paketeGesamt;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int anzahlUntGesamt;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int anzahlUntInPaket;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransBeginnArtEnum transArt;
        
        public BeginnTransaktionRequestBody() {
        }
        
        public BeginnTransaktionRequestBody(int bNR, string kNr, int nNr, int berichtsJahr, bool leermeldung, int paketeGesamt, int anzahlUntGesamt, int anzahlUntInPaket, BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransBeginnArtEnum transArt) {
            this.bNR = bNR;
            this.kNr = kNr;
            this.nNr = nNr;
            this.berichtsJahr = berichtsJahr;
            this.leermeldung = leermeldung;
            this.paketeGesamt = paketeGesamt;
            this.anzahlUntGesamt = anzahlUntGesamt;
            this.anzahlUntInPaket = anzahlUntInPaket;
            this.transArt = transArt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BeginnTransaktionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BeginnTransaktionResponse", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas", Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransaktionResponseBody Body;
        
        public BeginnTransaktionResponse() {
        }
        
        public BeginnTransaktionResponse(BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransaktionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public partial class BeginnTransaktionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransAntwort BeginnTransaktionResult;
        
        public BeginnTransaktionResponseBody() {
        }
        
        public BeginnTransaktionResponseBody(BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransAntwort BeginnTransaktionResult) {
            this.BeginnTransaktionResult = BeginnTransaktionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransNetzdatenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransNetzdaten", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas", Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransNetzdatenRequestBody Body;
        
        public TransNetzdatenRequest() {
        }
        
        public TransNetzdatenRequest(BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransNetzdatenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public partial class TransNetzdatenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string transNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.Netzdaten ndaten;
        
        public TransNetzdatenRequestBody() {
        }
        
        public TransNetzdatenRequestBody(string transNr, BNetzAWebServiceClient.WS_VersUnterbrechungGas.Netzdaten ndaten) {
            this.transNr = transNr;
            this.ndaten = ndaten;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransNetzdatenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransNetzdatenResponse", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas", Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransNetzdatenResponseBody Body;
        
        public TransNetzdatenResponse() {
        }
        
        public TransNetzdatenResponse(BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransNetzdatenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public partial class TransNetzdatenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.Antwort TransNetzdatenResult;
        
        public TransNetzdatenResponseBody() {
        }
        
        public TransNetzdatenResponseBody(BNetzAWebServiceClient.WS_VersUnterbrechungGas.Antwort TransNetzdatenResult) {
            this.TransNetzdatenResult = TransNetzdatenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransUnterbrechungenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransUnterbrechungen", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas", Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenRequestBody Body;
        
        public TransUnterbrechungenRequest() {
        }
        
        public TransUnterbrechungenRequest(BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public partial class TransUnterbrechungenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string transNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int paketNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.Unterbrechung[] udaten;
        
        public TransUnterbrechungenRequestBody() {
        }
        
        public TransUnterbrechungenRequestBody(string transNr, int paketNr, BNetzAWebServiceClient.WS_VersUnterbrechungGas.Unterbrechung[] udaten) {
            this.transNr = transNr;
            this.paketNr = paketNr;
            this.udaten = udaten;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransUnterbrechungenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransUnterbrechungenResponse", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas", Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenResponseBody Body;
        
        public TransUnterbrechungenResponse() {
        }
        
        public TransUnterbrechungenResponse(BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public partial class TransUnterbrechungenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenAntwort TransUnterbrechungenResult;
        
        public TransUnterbrechungenResponseBody() {
        }
        
        public TransUnterbrechungenResponseBody(BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenAntwort TransUnterbrechungenResult) {
            this.TransUnterbrechungenResult = TransUnterbrechungenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RueckgabeNetzdatenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RueckgabeNetzdaten", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas", Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenRequestBody Body;
        
        public RueckgabeNetzdatenRequest() {
        }
        
        public RueckgabeNetzdatenRequest(BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public partial class RueckgabeNetzdatenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string transNr;
        
        public RueckgabeNetzdatenRequestBody() {
        }
        
        public RueckgabeNetzdatenRequestBody(string transNr) {
            this.transNr = transNr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RueckgabeNetzdatenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RueckgabeNetzdatenResponse", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas", Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenResponseBody Body;
        
        public RueckgabeNetzdatenResponse() {
        }
        
        public RueckgabeNetzdatenResponse(BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public partial class RueckgabeNetzdatenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenAntwort RueckgabeNetzdatenResult;
        
        public RueckgabeNetzdatenResponseBody() {
        }
        
        public RueckgabeNetzdatenResponseBody(BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenAntwort RueckgabeNetzdatenResult) {
            this.RueckgabeNetzdatenResult = RueckgabeNetzdatenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RueckgabeUnterbrechungenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RueckgabeUnterbrechungen", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas", Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenRequestBody Body;
        
        public RueckgabeUnterbrechungenRequest() {
        }
        
        public RueckgabeUnterbrechungenRequest(BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public partial class RueckgabeUnterbrechungenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string transNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int paketNr;
        
        public RueckgabeUnterbrechungenRequestBody() {
        }
        
        public RueckgabeUnterbrechungenRequestBody(string transNr, int paketNr) {
            this.transNr = transNr;
            this.paketNr = paketNr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RueckgabeUnterbrechungenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RueckgabeUnterbrechungenResponse", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas", Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenResponseBody Body;
        
        public RueckgabeUnterbrechungenResponse() {
        }
        
        public RueckgabeUnterbrechungenResponse(BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public partial class RueckgabeUnterbrechungenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenAntwort RueckgabeUnterbrechungenResult;
        
        public RueckgabeUnterbrechungenResponseBody() {
        }
        
        public RueckgabeUnterbrechungenResponseBody(BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenAntwort RueckgabeUnterbrechungenResult) {
            this.RueckgabeUnterbrechungenResult = RueckgabeUnterbrechungenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AbschlussTransaktionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AbschlussTransaktion", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas", Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbschlussTransaktionRequestBody Body;
        
        public AbschlussTransaktionRequest() {
        }
        
        public AbschlussTransaktionRequest(BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbschlussTransaktionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public partial class AbschlussTransaktionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string transNr;
        
        public AbschlussTransaktionRequestBody() {
        }
        
        public AbschlussTransaktionRequestBody(string transNr) {
            this.transNr = transNr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AbschlussTransaktionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AbschlussTransaktionResponse", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas", Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbschlussTransaktionResponseBody Body;
        
        public AbschlussTransaktionResponse() {
        }
        
        public AbschlussTransaktionResponse(BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbschlussTransaktionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public partial class AbschlussTransaktionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.Antwort AbschlussTransaktionResult;
        
        public AbschlussTransaktionResponseBody() {
        }
        
        public AbschlussTransaktionResponseBody(BNetzAWebServiceClient.WS_VersUnterbrechungGas.Antwort AbschlussTransaktionResult) {
            this.AbschlussTransaktionResult = AbschlussTransaktionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AbbruchTransaktionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AbbruchTransaktion", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas", Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbbruchTransaktionRequestBody Body;
        
        public AbbruchTransaktionRequest() {
        }
        
        public AbbruchTransaktionRequest(BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbbruchTransaktionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public partial class AbbruchTransaktionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string transNr;
        
        public AbbruchTransaktionRequestBody() {
        }
        
        public AbbruchTransaktionRequestBody(string transNr) {
            this.transNr = transNr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AbbruchTransaktionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AbbruchTransaktionResponse", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas", Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbbruchTransaktionResponseBody Body;
        
        public AbbruchTransaktionResponse() {
        }
        
        public AbbruchTransaktionResponse(BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbbruchTransaktionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public partial class AbbruchTransaktionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.Antwort AbbruchTransaktionResult;
        
        public AbbruchTransaktionResponseBody() {
        }
        
        public AbbruchTransaktionResponseBody(BNetzAWebServiceClient.WS_VersUnterbrechungGas.Antwort AbbruchTransaktionResult) {
            this.AbbruchTransaktionResult = AbbruchTransaktionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ErgebnisPruefungRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ErgebnisPruefung", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas", Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.ErgebnisPruefungRequestBody Body;
        
        public ErgebnisPruefungRequest() {
        }
        
        public ErgebnisPruefungRequest(BNetzAWebServiceClient.WS_VersUnterbrechungGas.ErgebnisPruefungRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public partial class ErgebnisPruefungRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string transNr;
        
        public ErgebnisPruefungRequestBody() {
        }
        
        public ErgebnisPruefungRequestBody(string transNr) {
            this.transNr = transNr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ErgebnisPruefungResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ErgebnisPruefungResponse", Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas", Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.ErgebnisPruefungResponseBody Body;
        
        public ErgebnisPruefungResponse() {
        }
        
        public ErgebnisPruefungResponse(BNetzAWebServiceClient.WS_VersUnterbrechungGas.ErgebnisPruefungResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://app.bundesnetzagentur.de/WS_VersorgUnterbrGas")]
    public partial class ErgebnisPruefungResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.PruefAntwort ErgebnisPruefungResult;
        
        public ErgebnisPruefungResponseBody() {
        }
        
        public ErgebnisPruefungResponseBody(BNetzAWebServiceClient.WS_VersUnterbrechungGas.PruefAntwort ErgebnisPruefungResult) {
            this.ErgebnisPruefungResult = ErgebnisPruefungResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_VersUnterbrechungGasSoapChannel : BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_VersUnterbrechungGasSoapClient : System.ServiceModel.ClientBase<BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap>, BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap {
        
        public WS_VersUnterbrechungGasSoapClient() {
        }
        
        public WS_VersUnterbrechungGasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_VersUnterbrechungGasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_VersUnterbrechungGasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_VersUnterbrechungGasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransaktionResponse BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap.BeginnTransaktion(BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransaktionRequest request) {
            return base.Channel.BeginnTransaktion(request);
        }
        
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransAntwort BeginnTransaktion(int bNR, string kNr, int nNr, int berichtsJahr, bool leermeldung, int paketeGesamt, int anzahlUntGesamt, int anzahlUntInPaket, BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransBeginnArtEnum transArt) {
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransaktionRequest inValue = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransaktionRequest();
            inValue.Body = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransaktionRequestBody();
            inValue.Body.bNR = bNR;
            inValue.Body.kNr = kNr;
            inValue.Body.nNr = nNr;
            inValue.Body.berichtsJahr = berichtsJahr;
            inValue.Body.leermeldung = leermeldung;
            inValue.Body.paketeGesamt = paketeGesamt;
            inValue.Body.anzahlUntGesamt = anzahlUntGesamt;
            inValue.Body.anzahlUntInPaket = anzahlUntInPaket;
            inValue.Body.transArt = transArt;
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransaktionResponse retVal = ((BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap)(this)).BeginnTransaktion(inValue);
            return retVal.Body.BeginnTransaktionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransaktionResponse> BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap.BeginnTransaktionAsync(BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransaktionRequest request) {
            return base.Channel.BeginnTransaktionAsync(request);
        }
        
        public System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransaktionResponse> BeginnTransaktionAsync(int bNR, string kNr, int nNr, int berichtsJahr, bool leermeldung, int paketeGesamt, int anzahlUntGesamt, int anzahlUntInPaket, BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransBeginnArtEnum transArt) {
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransaktionRequest inValue = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransaktionRequest();
            inValue.Body = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.BeginnTransaktionRequestBody();
            inValue.Body.bNR = bNR;
            inValue.Body.kNr = kNr;
            inValue.Body.nNr = nNr;
            inValue.Body.berichtsJahr = berichtsJahr;
            inValue.Body.leermeldung = leermeldung;
            inValue.Body.paketeGesamt = paketeGesamt;
            inValue.Body.anzahlUntGesamt = anzahlUntGesamt;
            inValue.Body.anzahlUntInPaket = anzahlUntInPaket;
            inValue.Body.transArt = transArt;
            return ((BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap)(this)).BeginnTransaktionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransNetzdatenResponse BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap.TransNetzdaten(BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransNetzdatenRequest request) {
            return base.Channel.TransNetzdaten(request);
        }
        
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.Antwort TransNetzdaten(string transNr, BNetzAWebServiceClient.WS_VersUnterbrechungGas.Netzdaten ndaten) {
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransNetzdatenRequest inValue = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransNetzdatenRequest();
            inValue.Body = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransNetzdatenRequestBody();
            inValue.Body.transNr = transNr;
            inValue.Body.ndaten = ndaten;
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransNetzdatenResponse retVal = ((BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap)(this)).TransNetzdaten(inValue);
            return retVal.Body.TransNetzdatenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransNetzdatenResponse> BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap.TransNetzdatenAsync(BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransNetzdatenRequest request) {
            return base.Channel.TransNetzdatenAsync(request);
        }
        
        public System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransNetzdatenResponse> TransNetzdatenAsync(string transNr, BNetzAWebServiceClient.WS_VersUnterbrechungGas.Netzdaten ndaten) {
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransNetzdatenRequest inValue = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransNetzdatenRequest();
            inValue.Body = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransNetzdatenRequestBody();
            inValue.Body.transNr = transNr;
            inValue.Body.ndaten = ndaten;
            return ((BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap)(this)).TransNetzdatenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenResponse BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap.TransUnterbrechungen(BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenRequest request) {
            return base.Channel.TransUnterbrechungen(request);
        }
        
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenAntwort TransUnterbrechungen(string transNr, int paketNr, BNetzAWebServiceClient.WS_VersUnterbrechungGas.Unterbrechung[] udaten) {
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenRequest inValue = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenRequest();
            inValue.Body = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenRequestBody();
            inValue.Body.transNr = transNr;
            inValue.Body.paketNr = paketNr;
            inValue.Body.udaten = udaten;
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenResponse retVal = ((BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap)(this)).TransUnterbrechungen(inValue);
            return retVal.Body.TransUnterbrechungenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenResponse> BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap.TransUnterbrechungenAsync(BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenRequest request) {
            return base.Channel.TransUnterbrechungenAsync(request);
        }
        
        public System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenResponse> TransUnterbrechungenAsync(string transNr, int paketNr, BNetzAWebServiceClient.WS_VersUnterbrechungGas.Unterbrechung[] udaten) {
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenRequest inValue = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenRequest();
            inValue.Body = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.TransUnterbrechungenRequestBody();
            inValue.Body.transNr = transNr;
            inValue.Body.paketNr = paketNr;
            inValue.Body.udaten = udaten;
            return ((BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap)(this)).TransUnterbrechungenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenResponse BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap.RueckgabeNetzdaten(BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenRequest request) {
            return base.Channel.RueckgabeNetzdaten(request);
        }
        
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenAntwort RueckgabeNetzdaten(string transNr) {
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenRequest inValue = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenRequest();
            inValue.Body = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenRequestBody();
            inValue.Body.transNr = transNr;
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenResponse retVal = ((BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap)(this)).RueckgabeNetzdaten(inValue);
            return retVal.Body.RueckgabeNetzdatenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenResponse> BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap.RueckgabeNetzdatenAsync(BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenRequest request) {
            return base.Channel.RueckgabeNetzdatenAsync(request);
        }
        
        public System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenResponse> RueckgabeNetzdatenAsync(string transNr) {
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenRequest inValue = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenRequest();
            inValue.Body = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeNetzdatenRequestBody();
            inValue.Body.transNr = transNr;
            return ((BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap)(this)).RueckgabeNetzdatenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenResponse BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap.RueckgabeUnterbrechungen(BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenRequest request) {
            return base.Channel.RueckgabeUnterbrechungen(request);
        }
        
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenAntwort RueckgabeUnterbrechungen(string transNr, int paketNr) {
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenRequest inValue = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenRequest();
            inValue.Body = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenRequestBody();
            inValue.Body.transNr = transNr;
            inValue.Body.paketNr = paketNr;
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenResponse retVal = ((BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap)(this)).RueckgabeUnterbrechungen(inValue);
            return retVal.Body.RueckgabeUnterbrechungenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenResponse> BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap.RueckgabeUnterbrechungenAsync(BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenRequest request) {
            return base.Channel.RueckgabeUnterbrechungenAsync(request);
        }
        
        public System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenResponse> RueckgabeUnterbrechungenAsync(string transNr, int paketNr) {
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenRequest inValue = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenRequest();
            inValue.Body = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.RueckgabeUnterbrechungenRequestBody();
            inValue.Body.transNr = transNr;
            inValue.Body.paketNr = paketNr;
            return ((BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap)(this)).RueckgabeUnterbrechungenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbschlussTransaktionResponse BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap.AbschlussTransaktion(BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbschlussTransaktionRequest request) {
            return base.Channel.AbschlussTransaktion(request);
        }
        
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.Antwort AbschlussTransaktion(string transNr) {
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbschlussTransaktionRequest inValue = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbschlussTransaktionRequest();
            inValue.Body = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbschlussTransaktionRequestBody();
            inValue.Body.transNr = transNr;
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbschlussTransaktionResponse retVal = ((BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap)(this)).AbschlussTransaktion(inValue);
            return retVal.Body.AbschlussTransaktionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbschlussTransaktionResponse> BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap.AbschlussTransaktionAsync(BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbschlussTransaktionRequest request) {
            return base.Channel.AbschlussTransaktionAsync(request);
        }
        
        public System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbschlussTransaktionResponse> AbschlussTransaktionAsync(string transNr) {
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbschlussTransaktionRequest inValue = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbschlussTransaktionRequest();
            inValue.Body = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbschlussTransaktionRequestBody();
            inValue.Body.transNr = transNr;
            return ((BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap)(this)).AbschlussTransaktionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbbruchTransaktionResponse BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap.AbbruchTransaktion(BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbbruchTransaktionRequest request) {
            return base.Channel.AbbruchTransaktion(request);
        }
        
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.Antwort AbbruchTransaktion(string transNr) {
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbbruchTransaktionRequest inValue = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbbruchTransaktionRequest();
            inValue.Body = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbbruchTransaktionRequestBody();
            inValue.Body.transNr = transNr;
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbbruchTransaktionResponse retVal = ((BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap)(this)).AbbruchTransaktion(inValue);
            return retVal.Body.AbbruchTransaktionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbbruchTransaktionResponse> BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap.AbbruchTransaktionAsync(BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbbruchTransaktionRequest request) {
            return base.Channel.AbbruchTransaktionAsync(request);
        }
        
        public System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbbruchTransaktionResponse> AbbruchTransaktionAsync(string transNr) {
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbbruchTransaktionRequest inValue = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbbruchTransaktionRequest();
            inValue.Body = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.AbbruchTransaktionRequestBody();
            inValue.Body.transNr = transNr;
            return ((BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap)(this)).AbbruchTransaktionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BNetzAWebServiceClient.WS_VersUnterbrechungGas.ErgebnisPruefungResponse BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap.ErgebnisPruefung(BNetzAWebServiceClient.WS_VersUnterbrechungGas.ErgebnisPruefungRequest request) {
            return base.Channel.ErgebnisPruefung(request);
        }
        
        public BNetzAWebServiceClient.WS_VersUnterbrechungGas.PruefAntwort ErgebnisPruefung(string transNr) {
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.ErgebnisPruefungRequest inValue = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.ErgebnisPruefungRequest();
            inValue.Body = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.ErgebnisPruefungRequestBody();
            inValue.Body.transNr = transNr;
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.ErgebnisPruefungResponse retVal = ((BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap)(this)).ErgebnisPruefung(inValue);
            return retVal.Body.ErgebnisPruefungResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.ErgebnisPruefungResponse> BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap.ErgebnisPruefungAsync(BNetzAWebServiceClient.WS_VersUnterbrechungGas.ErgebnisPruefungRequest request) {
            return base.Channel.ErgebnisPruefungAsync(request);
        }
        
        public System.Threading.Tasks.Task<BNetzAWebServiceClient.WS_VersUnterbrechungGas.ErgebnisPruefungResponse> ErgebnisPruefungAsync(string transNr) {
            BNetzAWebServiceClient.WS_VersUnterbrechungGas.ErgebnisPruefungRequest inValue = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.ErgebnisPruefungRequest();
            inValue.Body = new BNetzAWebServiceClient.WS_VersUnterbrechungGas.ErgebnisPruefungRequestBody();
            inValue.Body.transNr = transNr;
            return ((BNetzAWebServiceClient.WS_VersUnterbrechungGas.WS_VersUnterbrechungGasSoap)(this)).ErgebnisPruefungAsync(inValue);
        }
    }
}
